# Generated by Django 2.2.6 on 2019-10-17 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Credits', models.PositiveSmallIntegerField()),
                ('DOC', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ- ]*$', 'Only')])),
                ('SecLastName', models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ- ]*$', 'Only uppercase letters.')])),
                ('Names', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ- ]*$', 'Only uppercase letters')])),
                ('PIN', models.CharField(max_length=4)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOE', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademyMgmt.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademyMgmt.Student')),
            ],
        ),
    ]
