# Generated by Django 2.2.5 on 2019-09-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademyMgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='Names',
        ),
    ]
