# Generated by Django 2.2.5 on 2019-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademyMgmt', '0002_auto_20190928_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PIN',
            field=models.CharField(max_length=4),
        ),
    ]
