# Generated by Django 2.2.6 on 2019-10-17 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademyMgmt', '0002_auto_20191017_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LastName',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ ]*$', 'Only uppercase letters')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Names',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ ]*$', 'Only uppercase letters')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='SecLastName',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZÑ ]*$', 'Only uppercase letters.')]),
        ),
    ]
