# Generated by Django 2.2.6 on 2019-10-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademyMgmt', '0007_auto_20191010_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='SecLastName',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
    ]
