# Generated by Django 2.2.6 on 2019-10-17 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademyMgmt', '0010_auto_20191017_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LastName',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('[A-ZÑ\\- ]', 'Only uppercase letter, dashes and spaces are allowed')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Names',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('[A-ZÑ\\- ]', 'Only uppercase letter, dashes and spaces are allowed')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='SecLastName',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('[A-ZÑ\\- ]', 'Only uppercase letter, dashes and spaces are allowed')]),
        ),
    ]
